#!/usr/bin/env python3
"""
Dependency manifest and installer helper for The Missing Interior.

This file is intentionally named ``requirements.py`` because it stores
dependency groups as Python data and can generate ordinary requirements
files when needed.

Examples
--------
Show available groups:
    python requirements.py --list-groups

Preview the recommended first-stage installation:
    python requirements.py --recommended

Write a pip-compatible requirements file:
    python requirements.py --recommended --write requirements-local.txt

Install the recommended first-stage stack:
    python requirements.py --recommended --install

Install specific groups:
    python requirements.py --group runtime --group science-core --install

Install every science group:
    python requirements.py --all-science --install

Notes
-----
* Nothing is installed unless ``--install`` is supplied.
* ``science-radar`` contains ARM Py-ART. On Windows, installing it through a
  dedicated conda-forge environment may be more reliable than pip.
* Scientific packages process observations; they do not determine the
  physical cause of an observation.
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from collections.abc import Iterable, Sequence
from pathlib import Path


PYTHON_MINIMUM = (3, 11)

RUNTIME = [
    "aiohttp>=3.9,<4",
    "aiosqlite>=0.20,<1",
    "alembic>=1.13,<2",
    "asyncpg>=0.29,<1",
    "discord.py>=2.4,<3",
    "rapidfuzz>=3,<4",
    "hypothesis>=6,<7",
    "openai>=2,<3",
    "pytest",
    "pydantic>=2.7,<3",
    "pydantic-settings>=2.7,<3",
    "PyYAML>=6.0.2,<7",
    "resvg_py>=0.3.3,<0.4",
    "SQLAlchemy[asyncio]>=2.0.30,<3",
]

DEV = [
    "pytest>=8.2,<9",
    "pytest-asyncio>=0.23,<1",
    "ruff>=0.6,<1",
]

SCIENCE_CORE = [
    "numpy",
    "scipy",
    "pandas",
    "xarray",
    "pint",
    "pint-xarray",
    "pyarrow",
    "scikit-learn",
    "statsmodels",
    "pandera",
    "networkx",
]

SCIENCE_FUSION = [
    "stonesoup",
]

SCIENCE_AVIATION = [
    "traffic",
    "pyModeS",
    "pyproj",
    "shapely",
    "astropy",
    "skyfield",
]

SCIENCE_ATMOSPHERE = [
    "metpy",
    "netCDF4",
    "h5py",
]

SCIENCE_RADAR = [
    "arm_pyart",
]

SCIENCE_SUBSURFACE = [
    "obspy",
    "PyWavelets",
]

SCIENCE_IMAGING = [
    "scikit-image",
    "opencv-python-headless",
]

SCIENCE_QUANTUM = [
    "qutip",
    "cvxpy",
]

SCIENCE_BAYESIAN = [
    "pymc",
    "arviz",
]

GROUPS: dict[str, list[str]] = {
    "runtime": RUNTIME,
    "dev": DEV,
    "science-core": SCIENCE_CORE,
    "science-fusion": SCIENCE_FUSION,
    "science-aviation": SCIENCE_AVIATION,
    "science-atmosphere": SCIENCE_ATMOSPHERE,
    "science-radar": SCIENCE_RADAR,
    "science-subsurface": SCIENCE_SUBSURFACE,
    "science-imaging": SCIENCE_IMAGING,
    "science-quantum": SCIENCE_QUANTUM,
    "science-bayesian": SCIENCE_BAYESIAN,
}

SCIENCE_GROUPS = tuple(name for name in GROUPS if name.startswith("science-"))

# First-stage stack recommended for Position 1 development.
RECOMMENDED_GROUPS = (
    "runtime",
    "science-core",
    "science-fusion",
    "science-aviation",
    "science-atmosphere",
)


def canonical_package_name(requirement: str) -> str:
    """Return a normalized package name for duplicate detection."""
    name = re.split(r"[<>=!~;\[\s]", requirement, maxsplit=1)[0]
    return re.sub(r"[-_.]+", "-", name).lower()


def flatten_requirements(group_names: Iterable[str]) -> list[str]:
    """
    Combine dependency groups while preserving order.

    When the same distribution appears more than once, the first declaration
    wins. This avoids duplicate entries such as pytest appearing in both the
    runtime and development groups.
    """
    requirements: list[str] = []
    seen: set[str] = set()

    for group_name in group_names:
        try:
            group = GROUPS[group_name]
        except KeyError as exc:
            raise ValueError(f"Unknown dependency group: {group_name}") from exc

        for requirement in group:
            key = canonical_package_name(requirement)
            if key in seen:
                continue
            seen.add(key)
            requirements.append(requirement)

    return requirements


def write_requirements_file(
    path: Path,
    requirements: Sequence[str],
    selected_groups: Sequence[str],
) -> None:
    """Write a conventional pip-compatible requirements text file."""
    path.parent.mkdir(parents=True, exist_ok=True)

    header = [
        "# Generated by requirements.py",
        f"# Python {PYTHON_MINIMUM[0]}.{PYTHON_MINIMUM[1]} or newer",
        f"# Groups: {', '.join(selected_groups)}",
        "",
    ]

    path.write_text(
        "\n".join([*header, *requirements, ""]),
        encoding="utf-8",
    )


def install_requirements(requirements: Sequence[str]) -> None:
    """Install requirements into the current Python environment."""
    if not requirements:
        raise ValueError("No requirements were selected.")

    command = [
        sys.executable,
        "-m",
        "pip",
        "install",
        "--upgrade",
        *requirements,
    ]

    print("Running:")
    print("  " + subprocess.list2cmdline(command))
    subprocess.run(command, check=True)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=(
            "Select, print, export, or install dependency groups for "
            "The Missing Interior."
        )
    )

    parser.add_argument(
        "--list-groups",
        action="store_true",
        help="Show every available dependency group and exit.",
    )
    parser.add_argument(
        "--group",
        action="append",
        choices=tuple(GROUPS),
        default=[],
        help="Select one dependency group. May be repeated.",
    )
    parser.add_argument(
        "--recommended",
        action="store_true",
        help="Select the recommended first-stage local analysis stack.",
    )
    parser.add_argument(
        "--all-science",
        action="store_true",
        help="Select every science dependency group.",
    )
    parser.add_argument(
        "--include-dev",
        action="store_true",
        help="Include development and testing dependencies.",
    )
    parser.add_argument(
        "--write",
        type=Path,
        metavar="PATH",
        help="Write the selected dependencies to a pip requirements file.",
    )
    parser.add_argument(
        "--install",
        action="store_true",
        help="Install the selected dependencies into the current environment.",
    )
    parser.add_argument(
        "--print",
        dest="print_requirements",
        action="store_true",
        help="Print the selected requirements, one per line.",
    )

    return parser


def selected_group_names(args: argparse.Namespace) -> list[str]:
    selected: list[str] = []

    if args.recommended:
        selected.extend(RECOMMENDED_GROUPS)

    if args.all_science:
        selected.extend(SCIENCE_GROUPS)

    selected.extend(args.group)

    if args.include_dev:
        selected.append("dev")

    # Preserve order while removing duplicate group names.
    return list(dict.fromkeys(selected))


def validate_python_version() -> None:
    if sys.version_info < PYTHON_MINIMUM:
        required = ".".join(map(str, PYTHON_MINIMUM))
        current = f"{sys.version_info.major}.{sys.version_info.minor}"
        raise RuntimeError(
            f"Python {required} or newer is required; current version is {current}."
        )


def main() -> int:
    parser = build_parser()
    args = parser.parse_args()

    validate_python_version()

    if args.list_groups:
        for name, requirements in GROUPS.items():
            marker = " [recommended]" if name in RECOMMENDED_GROUPS else ""
            print(f"{name}{marker}: {len(requirements)} package(s)")
        return 0

    groups = selected_group_names(args)

    if not groups:
        parser.error(
            "No dependency groups selected. Use --recommended, --all-science, "
            "or one or more --group options."
        )

    requirements = flatten_requirements(groups)

    if args.print_requirements or (not args.write and not args.install):
        print("\n".join(requirements))

    if args.write:
        write_requirements_file(args.write, requirements, groups)
        print(f"Wrote {len(requirements)} requirements to: {args.write}")

    if args.install:
        if "science-radar" in groups and sys.platform == "win32":
            print(
                "Warning: ARM Py-ART may install more reliably through "
                "conda-forge in a separate Windows environment.",
                file=sys.stderr,
            )
        install_requirements(requirements)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
